[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "cd /app/server && npm install",
  "cd /app/client && npm install"
]

[phases.build]
cmds = [
  "cd /app/client && node node_modules/vite/bin/vite.js build"
]

[start]
cmd = "cd /app/server && npm start"
